Better paths

diff --git a/webhook_start b/webhook_start
--- a/webhook_start
+++ b/webhook_start
@@ -1,3 +1,7 @@
 #!/bin/bash
-nohup ruby webhook.rb > webhook.log &
-echo "Server running. Check webhook.log for status."
+nohup ruby /home/gjulianm/latex_cd/webhook.rb &> /var/log/webhook.log &
+if [ $? -eq 0 ]; then
+	echo "Server running. Check webhook.log for status."
+else
+	echo "Error starting webserver"
+fi
